theme: minima
title: Katherine Lau's website
author: Katherine Lau
email: klau@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is my first website.
  
# social links
github_username:  BananaCookie7 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
